### PR TITLE
Remove members list

### PR DESCRIPTION
**Pull request by philtr**
Thinking about removing the members list. It doesn't really reflect who comes to the meetings and is a pain to keep updated. Thoughts?

/cc @fregas @agile @davidray @joshuawscott

### CODE REVIEW

**Comment by fregas** [comment]
Either that or convert it to a collection where you just have to maintain a list of github names.  But I'm fine with it either way.

**Comment by joshuawscott** [comment]
Fine with me

**Comment by agile** [comment]
+1

**Pull request merged**
